# Generated by Django 2.2.12 on 2020-05-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='head',
        ),
    ]
