# int float bool NoneType, str, tuple, frozenset
# list, dict, set



s = 'efsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfr' \
    'gdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdr' \
    'gdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgd' \
    'rgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfr' \
    'gdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefs' \
    'frgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdef' \
    'sfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgde' \
    'fsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrg' \
    'defsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdr' \
    'gdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgd' \
    'rgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdr' \
    'gdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgd' \
    'rgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgdefsfrgdrgdrgd'

print(s)
